/**
 * Created by Vitalii Leshchenko on 27.07.2017.
 */

import java.util.ArrayList;
import java.util.List;

/**
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 * By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
 */

public class EvenFibonacci {

    public static Integer sumOfEvenFibonacci(Integer limitValue) {
        List<Integer> storage = new ArrayList<>();
        Integer first = 1;
        Integer second = 2;
        Integer temporary = 0;
        storage.add(first);
        storage.add(second);

        while (first + second < limitValue) {
            temporary = first;
            first = second;
            second += temporary;
            storage.add(second);
        }
        return sumAll(storage);
    }

    private static Integer sumAll(List<Integer> storage) {
        Integer result = 0;
        for (Integer value : storage) {
            if (value % 2 == 0) {
                result += value;
            }
        }
        return result;
    }

}
